apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.name }}
data:
  MINIO_ENDPOINT: "http://lowry-minio-service:9000"
  BASE_FRONTEND_URL: "http://localhost"