{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.name }}-{{ .name }}-service
  namespace: {{ $.Values.name }}
spec:
  selector:
    app: {{ $.Values.name }}-{{ .name }}
  ports:
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}